image:
  repository: docker.io/onlywade/songdork
  pullPolicy: IfNotPresent
  tag: "master-318e698"
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 512Mi
twilio:
  phoneNumber: "+1 402 819 7071"
